### ISSUE TITLE
Warning when filtering and sorting results

### ISSUE THREAD

**Issue by h4rr9** [jvgrootveld/telescope-zoxide#1]
I'm getting this warning when I try to filter results by entering something in the prompt.

![image](https://user-images.githubusercontent.com/22914630/120476647-72184200-c3c8-11eb-98f8-f7c172e9726f.png)

![image](https://user-images.githubusercontent.com/22914630/120476294-0930ca00-c3c8-11eb-9be3-a9c2d6d08a6b.png)

**Comment by jvgrootveld** [comment]
@h4rr9 The issue is fixed
If you update to the new version, you should not get this error anymore.

**Comment by h4rr9** [comment]
@jvgrootveld Thank you!
