### ISSUE TITLE
"attempt to call a nil value" when using `:Telescope zoxide select` command, lua command works fine

### ISSUE THREAD

**Issue by macintacos** [jvgrootveld/telescope-zoxide#3]
I'm starting a brand new config and basically only have Telescope + a couple of Telescope extensions installed. When calling `:Telescope zoxide select` I immediately get an error:

```
E5108: Error executing lua ...ck/packer/start/telescope.nvim/lua/telescope/command.lua:90: attempt to call a nil value
```

Running `:lua require'telescope'.extensions.zoxide.list{}<CR>` works perfectly fine though, so I'll just use that for the time being. Thanks for making this!

**Comment by jvgrootveld** [comment]
@macintacos You are right, I didn't update the README correctly.
It should have been `:Telescope zoxide list` not `select`.

I will update the README shortly. Thanks for pointing it out!
