### ISSUE TITLE
Cannot get actions to start builtins in insert mode

### ISSUE THREAD

**Issue by petertriho** [jvgrootveld/telescope-zoxide#8]
I'm trying to start some of telescope's builtin functions using the selection path and the following config works:
```lua
local builtin = require("telescope.builtin")

local browse_files = function(selection)
    builtin.file_browser({ cwd = selection.path })
end

local find_files = function(selection)
    builtin.find_files({ cwd = selection.path, hidden = true })
end

local search_files = function(selection)
    builtin.live_grep({ cwd = selection.path })
end

require("telescope._extensions.zoxide.config").setup({
    mappings = {
        ["<C-b>"] = {
            action = browse_files
        },
        ["<C-f>"] = {
            action = find_files
        },
        ["<C-s>"] = {
            action = search_files
        }
    },
})
```
The problem I'm facing is that I can't seem to start them in `insert` mode. 

I have tried adding setting `initial_mode = "insert"` but this does not seem help. 

Thanks for the plugin! I'm happy to open a pull request with these added if you're open to it/not out of the scope of the plugin!

**Comment by jvgrootveld** [comment]
@petertriho Hadn't had time to reproduce the issue yet, but super thanks for the time and work! It's your idea and fix so it is fair to add your name to the code change. Please create a PR and I will review it!

_Don't forget to add the new option to the README_
